name: wayso_widget
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #network
  surrealdb: ^1.0.0
  dio: ^5.3.2
  #riverod
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  riverpod: ^2.5.1
  riverpod_generator: ^2.3.2
  #layout
  multi_split_view: ^3.0.1
  flutter_adaptive_scaffold: ^0.3.1
  #navigation
  go_router: ^14.0.2
  adaptive_progress_dialog: ^2.0.1
  flutter_portal: ^1.1.4
  intl: ^0.19.0
  printing: ^5.13.1
  pdf: ^3.10.1
  collection: ^1.18.0
  number_paginator: ^0.4.0
  flutter_typeahead: ^5.2.0
  textfield_tags: ^3.0.1
  wtf_sliding_sheet: ^1.1.3
  fl_chart: ^0.69.0
  sliding_up_panel: ^2.0.0+1
  future_progress_dialog: ^0.2.0
  file_picker: ^8.0.0+1
  # firebase
  firebase_storage: ^12.1.1
  firebase_core: ^3.2.0

  # datetime
  calendar_date_picker2: ^1.0.2
  flutter_date_range_picker: ^0.1.1
  in_date_utils: ^1.2.0+2
  vph_web_date_picker: ^0.0.4


  flutter_easyloading: ^3.0.5
  searchable_listview: ^2.10.1
  dynamic_tabbar: ^1.0.5
  csc_picker: ^0.2.7
  awesome_side_sheet: ^0.0.3
  easy_stepper: ^0.8.5+1
  # barcode: ^2.2.8
  # barcode_widget: ^2.0.4
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.0
  flutter_rust_bridge: ^2.4.0
  web_socket_channel: ^3.0.1
  fpdart: ^1.1.0
  onscreen_num_keyboard: ^1.0.4
  appwrite: ^13.0.0

  # interactive_bottom_sheet: ^1.0.0
  # wayso_widget:
  #   git:
  #     url: https://github.com/vinodh013/wayso_widgets
  #     ref: master #
  # image_network: ^2.5.4+1
  # date_picker_plus: ^2.0.3
  # flutter_date_pickers: ^0.4.2




dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
